### PR TITLE
Move more towards composition, not inheritance

### PR DESCRIPTION
**Pull request by ronshapiro**
Since there's no hook into `onDraw(Canvas)` some level of inheritance is necessary, but this would allow another user to add the functionality into `MyShinyNewTextViewNowWithLineNumbers`.

Note, it's not tested since I didn't have r22 of the support lib. Mostly just copy/paste of code into DrawingEngine and then qualifying methods with `textView.`. Might have a couple bounds checking on initialization errors, but they'll likely come up early.

### CODE REVIEW

**Comment by mgottein** [comment]
This is a tricky problem to solve. Unfortunately, the ExposesPaddingOffset trick doesn't pass the java compiler and every TextView subclass that uses DrawingEngine either needs to forward DrawingEngine's methods or expose the DrawingEngine itself.

**Comment by ronshapiro** [comment]
Yea, it's definitely not a great solution. Tough problem to truly solve correctly :-/

**Comment by mgottein** [comment]
also there are implementation artifacts of TextView creeping in. like onTextChanged being called before you think it would

**Comment by mgottein** [comment]
yea i dunno sry

**Pull request closed without merging**
